export const sources = [
  {
    id: "SRC-001",
    channelName: "Creator Insider",
    url: "https://www.youtube.com/@CreatorInsider",
    category: "Chính sách YouTube",
    ownerType: "Chính chủ",
    subscribers: "750K",
    score: 96,
    verdict: "Nên tham khảo",
    reason: "Kênh chính thức của đội ngũ YouTube, nội dung cập nhật trực tiếp từ nền tảng.",
    lastChecked: "Hôm nay, 10:20",
  },
  {
    id: "SRC-002",
    channelName: "YouTube Creators",
    url: "https://www.youtube.com/@youtubecreators",
    category: "Hướng dẫn creator",
    ownerType: "Chính chủ",
    subscribers: "6.8M",
    score: 94,
    verdict: "Nên tham khảo",
    reason: "Nguồn chính thức, phù hợp để theo dõi tính năng và quy định cho nhà sáng tạo.",
    lastChecked: "Hôm qua, 16:45",
  },
  {
    id: "SRC-003",
    channelName: "Growth Tips Reupload",
    url: "https://www.youtube.com/@growthtips-reupload",
    category: "Tăng trưởng kênh",
    ownerType: "Không rõ nguồn",
    subscribers: "42K",
    score: 48,
    verdict: "Cần kiểm tra",
    reason: "Nhiều video tổng hợp lại, chưa xác minh được chủ sở hữu nội dung gốc.",
    lastChecked: "25/07/2026, 09:12",
  },
  {
    id: "SRC-004",
    channelName: "Policy Summary Shorts",
    url: "https://www.youtube.com/@policysummaryshorts",
    category: "Tóm tắt chính sách",
    ownerType: "Bên thứ ba",
    subscribers: "18K",
    score: 32,
    verdict: "Không nên tham khảo",
    reason: "Thông tin thiếu nguồn dẫn, tiêu đề phóng đại và không có liên kết tài liệu chính thức.",
    lastChecked: "24/07/2026, 20:30",
  },
];

export const checklist = [
  "Có dấu hiệu là kênh chính thức hoặc có liên kết xác minh rõ ràng",
  "Nội dung có nguồn dẫn từ YouTube Help, Creator Academy hoặc blog chính thức",
  "Không reup nội dung, không dùng tiêu đề gây hiểu nhầm",
  "Tần suất cập nhật đều và thông tin không lỗi thời",
  "Bình luận/feedback cộng đồng không cảnh báo lừa đảo hoặc spam",
];

export const countries = ["Việt Nam", "United States", "Thailand", "Indonesia", "Japan", "Korea"];

export const trendingKeywords = [
  {
    keyword: "AI tạo video shorts",
    country: "Việt Nam",
    category: "Công nghệ",
    searchVolume: "128K",
    growth: "+42%",
    competition: "Trung bình",
    suggestion: "Nên tham khảo",
  },
  {
    keyword: "kiếm tiền youtube 2026",
    country: "Việt Nam",
    category: "Creator",
    searchVolume: "94K",
    growth: "+31%",
    competition: "Cao",
    suggestion: "Cần lọc nguồn",
  },
  {
    keyword: "faceless youtube channel ideas",
    country: "United States",
    category: "Business",
    searchVolume: "310K",
    growth: "+27%",
    competition: "Cao",
    suggestion: "Nên tham khảo",
  },
  {
    keyword: "youtube shorts algorithm",
    country: "United States",
    category: "Creator",
    searchVolume: "265K",
    growth: "+18%",
    competition: "Trung bình",
    suggestion: "Nên tham khảo",
  },
  {
    keyword: "review đồ gia dụng mini",
    country: "Thailand",
    category: "Review",
    searchVolume: "76K",
    growth: "+36%",
    competition: "Thấp",
    suggestion: "Nên khai thác",
  },
];
